spring:
  main:
    web-application-type: none
  config:
    import: optional:classpath:application-local.yml

banxico:
  token: ${BANXICO_TOKEN}

dynamics:
  base-url: ${DYNAMICS_BASE_URL:https://olnatura-produccion.operations.dynamics.com}
  tenant-id: ${DYNAMICS_TENANT_ID}
  client-id: ${DYNAMICS_CLIENT_ID}
  client-secret: ${DYNAMICS_CLIENT_SECRET}
  scope: ${DYNAMICS_SCOPE:https://olnatura-produccion.operations.dynamics.com/.default}

logging:
  level:
    root: INFO
    com.olnatura: INFO
